/*
 * This source file was generated by the Gradle 'init' task
 */

#include <queue>
#include <memory>
#include <ctime>
#include "Patient.h"
#include "PatientRecord.h"
#include "app.h"
#include "IntakeForm.h"


int main () {
    std::priority_queue<
        PatientRecord,
        std::vector<PatientRecord>,
        PatientComparator
    > erQueue;

    IntakeForm form;
    char more = 'y';
    while(more == 'y' || more == 'Y') {
        auto patient = form.collect();
        PatientRecord record(std::time(nullptr), patient);
        erQueue.push(record);

        std::cout << "Add another patient? (y/n): ";
        std::cin >> more;
        std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
    }


    while (!erQueue.empty()) {
        auto next = erQueue.top();
        next.patient->displayInfo();
        erQueue.pop();
    }


    return 0;
}
