/*
 * This source file was generated by the Gradle 'init' task
 */

#include <queue>
#include <memory>
#include <ctime>
#include <limits>
#include "Patient.h"
#include "PatientRecord.h"
#include "app.h"
#include "IntakeForm.h"


int main () {
    std::priority_queue<
        PatientRecord,
        std::vector<PatientRecord>,
        PatientComparator
    > erQueue;

    IntakeForm form;
    char more = 'y';
    while(true) {
        auto patient = form.collect();
        PatientRecord record(std::time(nullptr), patient);
        erQueue.push(record);

        std::string line;
        std::cout << "Add another patient? (y/n): ";
        std::getline(std::cin, line);

        if (!line.empty()) {
            more = line[0];
        } else {
            more = 'n';
        }

        if (more != 'y' && more != 'Y') {
            break;
        }
    }

    while (!erQueue.empty()) {
        auto next = erQueue.top();
        next.patient->displayInfo();
        erQueue.pop();
    }

    return 0;
}
